### ISSUE TITLE
extended locale variants use _ (underscore) instead of - (dash)

### ISSUE THREAD

**Issue by monzttr** [athyuttamre/locale-switcher#1]
Is it possible to use - (dash) instead of _ (underscore) for extended locale variants? E.g. fr-ca instead of fr_ca.

Or if it's possible to allow the user pick between the two, that would be great. 

Thanks!

**Comment by athyuttamre** [comment]
Thank you for reporting, this has now been fixed. I've submitted the extension for review and it'll be published and updated automatically in a few days.

**Comment by monzttr** [comment]
thanks @athyuttamre !!!
