### ISSUE TITLE
Microsoft Azure administration sites not working anymore

### ISSUE THREAD

**Issue by achimismaili** [athyuttamre/locale-switcher#12]
Dear sirs, 
I love your extension a lot, it just has the right mix of UX, functionality and not too many features. I have it installed on Google Chrome and on the new MS Edge based on Chromium engine. (My setup is a decent Windows 10 company computer with vpn only company proxy.) 

Unfortunately, I am no longer able to use it, because it breaks at least two of my most required web sites/portals: 

**Azure DevOps user list** 
In Azure DevOps (https://dev.azure.com) when you create a free organization (, you only need a free microsoft account to do that, ) and you want to list the users under https://dev.azure.com/[your organization]/_settings/users, the list of users in your organization is not loaded, when your extension is installed. :( 

**Azure Portal AAD user list** 
When you have an Azure Active Directory (you can get it for free for 12 months, you only need a free microsoft account) and you want to list all users in your portal under [https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/MsGraphUsers](https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/MsGraphUsers) then the users list is not loaded, instead you get an error-message (and in developer network tools, you see, that some XHR requests are failing). Basically, a lot of additional functionality in the [Azure portal](https://portal.azure.com) is not working with the extension, you see that by just opening the portal dashboard... :( 

Right after removing the extension, everything works fine again. I am really sorry, that this way I can't use it anymore for all other web sites.

It would help me, if you add a functionality to remove some sites/domains from being affected by the extension.

ps: 
I just saw, that you mentioned you are not notified of issues in the [chrome extension store](https://chrome.google.com/webstore/detail/locale-switcher), so I put my issue here and removed it there.

I am just mentioning that all this is free to set up not to try to sell anything but to let you know that it could be reproduced without any cost.

**Comment by cupcakearmy** [comment]
Should be fixed in 1.0.0 as locale are only on a tab scope. related to #8 .
