### ISSUE TITLE
How do you change the locale with this extension?

### ISSUE THREAD

**Issue by mabbas64** [athyuttamre/locale-switcher#13]
Hi,

I couldn't find any usage info on the addon's page or the github readme here. Not sure I'm missing the obvious but could you please add a line or two on the addon page explaining where exactly this addon can be used/adjusted from?

**Comment by cupcakearmy** [comment]
For now: Basically click on the extension in the browser and then select your language.

I'll do a screencap video for the next release, so it can't be missed

**Comment by cupcakearmy** [comment]
@mabbas64 feel free to reopen if still needed.
