### ISSUE TITLE
Allow favoriting certain locales

### ISSUE THREAD

**Issue by athyuttamre** [athyuttamre/locale-switcher#2]
From the support forum:

> I really like your extension - thanks! One suggestion: a previous language switcher extension I used had a feature where you could customize the list of languages that you saw. I don't really need the ability to fully customize the list, but it would be really useful to have the list of favorites or recently used languages at the top of the list, that way it would be even easier to switch between them. We support 7 languages currently in our product, so being able to flip between those 7 (versus searching each time) would be great!

**Comment by kewalter** [comment]
We may be having our QA team toggle back and forth between languages to test our site.  A favorites list would be amazingly helpful for us.

**Comment by nmg196** [comment]
I'd love this too! I think most people will only be switching between 2 (or maybe 3) languages and it's kind of a pain if the language you most often want to switch to isn't on the list.

**Comment by janhasnocap** [comment]
One of the best locale switch extension I used 👍 , but I'm really missing this feature. Any change this will be added @athyuttamre  ?

**Comment by athyuttamre** [comment]
Sorry folks, I haven't been actively maintaining this extension. Feel free to fork it and add features.

**Comment by cholley** [comment]
the old version can set gloable locale for chrome, it is very nice feature, but new version remove this feature.
Can you add a gloable option to set locale fixed, even restart the chrome, it can still work for all tabs, no need  to setup for each tab.

Thanks!
