### ISSUE TITLE
Locales in wrong format _ vs -

### ISSUE THREAD

**Issue by DennieBroucke** [athyuttamre/locale-switcher#28]
When using the new version 1.0.0, it seems the locales are in the wrong format.
The values are now  language_country while it is supposed to be language-country. The mistake is probably because of a scraping error using locale planet; the label is with _ but it refers to a page with - in the URI.
Reference for correct format :  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

**Comment by cupcakearmy** [comment]
My bad! Thanks for reporting. Will fix immediately

**Comment by cupcakearmy** [comment]
Submitted to both stores, new version should be available soon
