### ISSUE TITLE
Can you add a globle option for locale?

### ISSUE THREAD

**Issue by cholley** [athyuttamre/locale-switcher#29]
Thanks for your efforts!

I used old version for very long time and it works very good!
Now it is updated to latest version and the gloable locale is missing, everytime I open chrome, I need to setup the locale for each tab, it is killing me.

Why I can not change the default language of chrome? well, my english is not good, display everything on chrome in english is not friendly to me. But I have specially needs for locale, many website I use needs to interact with browser in english, otherwise it will  declined the service and cause other issue.

So, if possible, can you help to release old version zip file and disable auto update? Or add a globle option to get the locale fixed to specific value like old version and no need to setup everytime after restart chrome?

Thanks so much again! Best wishes to you!

**Comment by cupcakearmy** [comment]
Hey there!
We removed the global option since most people prefer a tab based approach.
However it could be added as a feature. Will think about the design, but won't be in the coming days probably

In the mean time: https://github.com/locale-switcher/locale-switcher/archive/1a14ec74105df7ef77b14df7fe08d95bba76f480.zip
This is the old code if you want to use it.

**Comment by athyuttamre** [comment]
You can also change the overall browser locale manually at `chrome://settings/?search=language` if you want to permanently change the language of your browser.

**Comment by cholley** [comment]
> 

Hi,

The zip file is not working, can you help to check it?
it shows error after load unpacked extension:
![image](https://user-images.githubusercontent.com/10412149/149060605-c5074a46-6616-4c23-a4bc-e628eb1ca9a4.png)
![image](https://user-images.githubusercontent.com/10412149/149060673-3f96f042-97e0-441b-bd03-cca02108609a.png)

Click it, show nothing:
![image](https://user-images.githubusercontent.com/10412149/149060627-a91d6925-6395-4bb4-8b5d-3211e4633563.png)

It can not show any locale values.

Thanks for your help!

**Comment by oplle** [comment]
> > 
> 
> Hi,
> 
> The zip file is not working, can you help to check it? it shows error after load unpacked extension: ![image](https://user-images.githubusercontent.com/10412149/149060605-c5074a46-6616-4c23-a4bc-e628eb1ca9a4.png) ![image](https://user-images.githubusercontent.com/10412149/149060673-3f96f042-97e0-441b-bd03-cca02108609a.png)
> 
> Click it, show nothing: ![image](https://user-images.githubusercontent.com/10412149/149060627-a91d6925-6395-4bb4-8b5d-3211e4633563.png)
> 
> It can not show any locale values.
> 
> Thanks for your help!

I try to repackage, but I still have the same problem. I like the old version

**Comment by oplle** [comment]
> You can also change the overall browser locale manually at `chrome://settings/?search=language` if you want to permanently change the language of your browser.

I just don't want to expose my privacy

**Comment by RZzHh** [comment]
If you want to use the old version, please clone the old warehouse from the link above and build it manually
The following operating environments are required
`Python Nodejs yarn Parcel`

Move to the root of the source code and enter the following command
`npm install`
`yarn release`
The built plugin will be generated in the /build directory and loaded into the browser afterwards
Or you can use the version I compile
[release.zip](https://github.com/locale-switcher/locale-switcher/files/7980511/release.zip)

If you have any other questions, please reply to me

**Comment by cupcakearmy** [comment]
Added back in 1.2.0

**Comment by oplle** [comment]
> If you want to use the old version, please clone the old warehouse from the link above and build it manually The following operating environments are required `Python Nodejs yarn Parcel`
> 
> Move to the root of the source code and enter the following command `npm install` `yarn release` The built plugin will be generated in the /build directory and loaded into the browser afterwards Or you can use the version I compile [release.zip](https://github.com/locale-switcher/locale-switcher/files/7980511/release.zip)
> 
> If you have any other questions, please reply to me

What you offer is very good, Chrome77 is as effective.
@cupcakearmy 1.2.0 Chrome77 Open is blank

**Comment by cupcakearmy** [comment]
@oplle in chrome 77 the extension does not work at all?

**Comment by oplle** [comment]
@cupcakearmy After clicking the icon, it is blank. https://imgur.com/tgNvuRr

**Comment by oplle** [comment]
After clicking the icon, it is blank.

**Comment by cupcakearmy** [comment]
@oplle want to open an issue? and if you could get some debug logs that would be incredible, chrome does not offer 77 as a download anymore :/

**Comment by oplle** [comment]
@cupcakearmy I use the old version shared by @PFCraft-box , I can run perfectly, never mind
