### ISSUE TITLE
Option to use localstorage and not session storage

### ISSUE THREAD

**Issue by fillo-it** [athyuttamre/locale-switcher#32]
Hello, I'm having problems with this new version, with the old one, once set up locale switcher to work with a specific website and once set the first time the locale for that website, each time I open the browser the locale was automatically set to the last used. With this new version, each time I open the browser for that website I must set locale again. Is there a way to get it work as before?
Thank you for your support!

**Comment by cupcakearmy** [comment]
Hey there. Before it was global, we could add a feature that persists the language over localstorage and not the session, so it would stay persisent over the same domain

**Comment by fillo-it** [comment]
yes thank you it would be great!

**Comment by cupcakearmy** [comment]
Should be fixed by in 1.2.0
