### ISSUE TITLE
Missing zh-CN - Chinese Simplified -  translation code

### ISSUE THREAD

**Issue by NikS-44** [athyuttamre/locale-switcher#35]
I know the translation code gets scraped directly from Locale Planet, but I was wondering if it would be possible to add the zh-CN translation code in manually? I believe this language code was part of the previous version, but is no longer available in this version. Thanks for your work on this extension!

**Comment by cupcakearmy** [comment]
Definetely!

```
"zh-CN": {
    "name": "Chinese (China)",
    "native": "中文(中国)"
  },
```

Is this correct?

**Comment by NikS-44** [comment]
Yes, that looks good to me. I can't confirm the native Chinese though :). Thank you very much!
