### ISSUE TITLE
delete the source map.

### ISSUE THREAD

**Issue by katsumi-axis** [athyuttamre/locale-switcher#37]
Thanks for the great extension.
I have hit the following problem.
<img width="1070" alt="スクリーンショット 2022-03-05 17 47 26" src="https://user-images.githubusercontent.com/9552135/156875921-6a1469b9-7b3c-4858-bde3-ca4487b1d929.png">

I have found the following problem, so I suggest to add "--no-source-maps" at build time.

Excuse my bad English.

**Comment by cupcakearmy** [comment]
Yes, absolutely! Thanks :)

**Comment by cupcakearmy** [comment]
Uploaded the fix
