### ISSUE TITLE
Content zooms-in on every launch

### ISSUE THREAD

**Issue by miran248** [athyuttamre/locale-switcher#40]
Any idea why is it happening?
![locale-switcher-1 2 3-css-bug-2022-07-11](https://user-images.githubusercontent.com/32389245/178302721-75404f62-6e4c-4548-9fa1-bd17a56e7a9a.gif)
The ui stabilizes after a few seconds, but still..

**Comment by cupcakearmy** [comment]
This should not be a thing xD
What browser and version are you using?

**Comment by miran248** [comment]
Hey,
It was chrome on macos, no idea which versions.
I have just tried it again and it looked fine, so either the bug was resolved already or there was something else at play.
