### ISSUE TITLE
Keyboard shortcut conflict

### ISSUE THREAD

**Issue by fabiosoft** [athyuttamre/locale-switcher#41]
Finally i found this amazing extension, but i have a issue during my daily use.

Please use another shortcut, or let the user decide if it's enabled. The "L" shortcut is conflicting with my Bitwarden extension i use for password completion, which i use more often (once i decided the locale, i never change it).

**Comment by cupcakearmy** [comment]
Hey, you can customize this in the settings both in firefox and chrome :)


https://user-images.githubusercontent.com/14948823/194898832-20c5d1d9-1d1f-465a-886a-93f1e1e90ecc.mp4


https://user-images.githubusercontent.com/14948823/194898850-4e1773e1-0260-4ea2-8db8-0f096daba1d7.mp4

**Comment by fabiosoft** [comment]
Amazing! Thanks, i did not know this browser feature
