### ISSUE TITLE
Please add Hebrew Local (iw) to the list

### ISSUE THREAD

**Issue by johnnythegodling** [athyuttamre/locale-switcher#48]
Please could you add Hebrew (iw) to the locales list? You have "he" but iw is also used.

**Comment by cupcakearmy** [comment]
The one you are suggesting is deprecated since 1989 in theory

https://www.loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=184

However it could be nice to have user defined, additional codes that one could add. #46
Thoughts?

**Comment by jtien** [comment]
Yes please, you are correct in theory, but indeed there are some applications out there that specifically cite iw when displaying Hebrew and hence my original request

**Comment by cupcakearmy** [comment]
Ok, I'm going to close this in favour to #46 then
