### ISSUE TITLE
Misplaced "Reset locale" button in menu

### ISSUE THREAD

**Issue by shchadilov** [athyuttamre/locale-switcher#6]
See screenshot, "Reset locale" button extends beyond the right border of drop-down menu.
openSUSE Leap 15.1
Chrome 80.0.3987.87 obtained from Google repository.
Addon v. 0.1.1

![Screenshot_20200210_192444](https://user-images.githubusercontent.com/22318514/74169049-badc4280-4c3b-11ea-8780-b387bb050e2b.png)

**Comment by athyuttamre** [comment]
Thanks for reporting! I will take a look later today.
