### ISSUE TITLE
Allow changing locale only for active tab

### ISSUE THREAD

**Issue by athyuttamre** [athyuttamre/locale-switcher#8]
From user request:

![image](https://user-images.githubusercontent.com/1485350/81002328-e49da380-8dfd-11ea-94fd-056f5ade14b1.png)

**Comment by qwc** [comment]
That's in fact what I am looking for, no extension I found does that.

Change the language only for a specific tab and even be able to set it as default for that tab and/or url. What means saving that selection somewhere.

**Comment by cupcakearmy** [comment]
Will be in the next release
