### ISSUE TITLE
es-419 for Latin American Spanish

### ISSUE THREAD

**Issue by chrisgarrity** [athyuttamre/locale-switcher#9]
Would you consider adding the `es-419` locale for Latin American Spanish. It would be really helpful for testing when we don't distinguish between different locales in the America's but we do have a difference with `es-ES`

**Comment by cupcakearmy** [comment]
Definetely!

**Comment by chrisgarrity** [comment]
@cupcakearmy a belated thank you! This has already come in useful several times.
